### ISSUE TITLE
static predefined positions

### ISSUE THREAD

**Issue by SA8R1NA** [stg-tud/bp2022_netlab#8]
# User Story

As a user I want the possibility to have static predefined positions

# Description

As a user I want the possibility to have static predefined positions, so that i start with the same starting conditions and properties for each experiment run.
I am able to set nodegroup movement as "static-predifend" with a list of all positions. (Group view)

# Acceptance criteria
- [ ] input data from configuration file remains the same after a run 
- [ ] Data changes only by manually changing the configuration file
- [ ] there is a list for every node with their static position which can be extracted in CSV 
- [ ] I can activate the field "Static-predefined" in the config file

**Comment by ebinf** [comment]
Also for The ONE
